version: "2.1"

services:
    docker_compose_ui:
        restart: unless-stopped
        image: francescou/docker-compose-ui:1.13.0
        container_name: docker_compose_ui
        hostname: docker_compose_ui
        working_dir: /workspace
        environment:
        - 'WEB_CONSOLE_PATTERN=/web-console/?cid={containerName}&cmd={command}'
        #working_dir: /home/user/docker-compose-ui/demo-projects
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${COMPOSE_UI_PROJECT_FOLDER:-/opt/docker-compose-projects/}:/workspace
    web_console:
        image: bitbull/docker-exec-web-console
        environment:
        - 'CONTEXT_PATH=/web-console/'
        read_only: true
        restart: unless-stopped
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    
    authed_nginx:
      image: quay.io/dtan4/nginx-basic-auth-proxy:latest
      ports:
        - ${COMPOSE_UI_PORT:-8080}:80
      environment:
        - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME:-admin}
        - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD:-admin}
        - PROXY_PASS=http://nginx/    
    
    nginx:
        image: nginx:alpine
        read_only: true
        restart: unless-stopped
        volumes:
          - ./default.conf:/etc/nginx/conf.d/default.conf:ro
          - /var/cache/nginx/
          - /var/run/
          - /logs/
